config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :authors
  get 'home/index'
  root to: "readers/home#index"
  get '/blog/:id' => 'readers/posts#show', as: :blog_post
  
  scope module: 'authors' do
    resources :posts do
     resources :elements
   end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user
  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image','video-embed'] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  belongs_to :author
  has_many :elements

  has_one_attached :header_image

  validates_presence_of :title, :description
  validates_length_of :description, within: 50..250

  scope :published, -> do
    where(published: true)
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_query

  def set_query
    @query = Post.ransack(params[:q])
  end
end  

app/controllers/authors/albums.rb
require 'rubygems'
require 'httparty'

class MicrourbRest
  include HTTParty
  base_uri 'https://jsonplaceholder.typicode.com'

  def albums
    self.class.get('/albums')
  end
end

microurb_rest = MicrourbRest.new
puts microurb_rest.albums

app/controllers/authors/elements_controller.rb
module Authors
class ElementsController < AuthorsController
  before_action :set_post
  before_action :set_element, only: [:update, :destroy]


  # POST /elements
  def create
    @element = @post.elements.build(element_params)

    if @element.save
      notice = nil
    else
      notice = @element.errors.full_messages.join(". ") << "."
    end
    redirect_to edit_post_path(@post), notice: notice
  end

  # PATCH/PUT /elements/1
  def update
    @element.update(element_params)
    redirect_to edit_post_path(@element.post)
  end

  # DELETE /elements/1
  def destroy
    @element.destroy
    redirect_to edit_post_path(@element.post)
  end

  private

  def set_post
    @post = current_author.posts.find(params[:post_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: [:edit, :update, :destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.update(post_params)
      redirect_to edit_post_path(@post)
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
    end
  end

app/controllers/authors/todos.rb
require 'rubygems'
require 'httparty'

class MicrourbRest
  include HTTParty
  base_uri 'https://jsonplaceholder.typicode.com'

  def todos
    self.class.get('/todos')
  end
end

microurb_rest = MicrourbRest.new
puts microurb_rest.todos

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
module Readers
  class PostsController < ReadersController

    def show
      @post = Post.published.friendly.find(params[:id])
    end

  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  layout 'readers'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from
        being saved:</h2>

        <!-- Prints out error message if required -->
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

<!--Sets up the title of the post-->
    <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <% form.error_for :title %>
  </div>

<!--Sets up the description of the post-->
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
      <% form.error_for :description %>
  </div>

<!--Sets up the header image of the post-->
  <div class="form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image %>
    <div class="mt-1">
      <small>Current image:</small>
        <% if post.header_image.present? %>
        <%= image_tag(post.header_image, width: '100%') %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
<div class="col-md-4">
  <!--Button to click back to the view posts page-->
  <%= link_to 'Back', posts_path, class: 'btn btn-secondary mb-3' %>
  <div class="card">
    <div class="card-header">
      <h6 class='card-title mb-0'>Editing Clothes Review</h6>
    </div>
    <div class="card-body">
      <%= render 'form', post: @post %>
    </div>
    <div class="card-footer">
      <!--If the post is published the button will change to Unpublished
       If the post is unpublished the button will appear as Publish-->
      <% if @post.published? %>
        <a href="#"
          class='btn btn-secondary btn-block'
          data-reflex='click->PublisherReflex#unpublish'
          data-post-id='<%= @post.id %>'>
          Unpublish
        </a>
      <% else %>
        <a href="#"
          class='btn btn-dark btn-block'
          data-reflex='click->PublisherReflex#publish'
          data-post-id='<%= @post.id %>'>
          Publish
        </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="mb-3">
      <!--Button that allows user to add a paragraph section to their post-->
      <%= form_with(model: [@post, @element], html: { class: 'float-left mr-1' }) do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= form.submit "Paragraph", class: "btn btn-dark" %>
      <% end %>
      <!--Button that allows user to add an image section to their post-->
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= form.submit "Image", class: "btn btn-dark" %>
      <% end %>
    </div>
    <div class="card mb-5">
      <div class="card-header text-right">
        <!--This determines the published status, if the post is published it will say publishedand how much time time ago
        If the post is unpublished the statuts above the post says unpublished-->
        <%if @post.published? %>
          <b>Published</b> <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>

      <!--The message in the paragraph tag comes up when no paragraph or image has been added to the post-->
        <div class="card-body pt-5" data-controller="elements">
        <% if @post.elements.none? {|element| element.persisted? } %>
        <div class="p-4 text-center">
          <h2 class='text-secondary'>
            <i class="fa-solid fa-circle-arrow-up"></i>
          </h2>
          <p>Click the buttons above to add information to your clothing review</p>
        </div>
        <% else %>
        <!--(Stimulus Reflex Gem)Allows for the sorting of elements e.g dragging a paragraph above an image than was previously below the image-->
          <ul id='elements' data-action="drop->elements#sort">
            <% @post.elements.order(position: :asc).each do |element| %>
              <% if element.persisted? %>
                <li data-id="<%= element.id %>" class='element-item'>
                <% if element.paragraph? %>
                  <div class="mb-4 p-3 paragraph">
                    <div class="paragraph-content">
                      <% if element.content.present? %>
                      <%= element.content %>
                      <% else %>
                      Click to add product review.
                      <% end %>
                    </div>
                    <div class="paragraph-form d-none" id='element—<%= element.id %>—form'>
                      <%= form_with(model: [@post, element]) do |form| %>
                        <%= form.rich_text_area :content %>
                        <div class="mt-3 d-flex justify-content-between">
                          <div>
                          <!--Saves the post-->
                          <%= form.submit "Save", class: "btn btn-primary" %>
                          <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                          </div>
                          <!--Deletes the post-->
                          <%= link_to 'Delete', post_element_path(@post, element), method:
                          :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?" } %>
                        </div>
                      <% end %>
                  </div>
                </div>
                <% elsif element.image? %>
                <div class="mb-4 p-3 image">
                  <% if element.image.present? %>
                    <div>
                      <%= image_tag(element.image) %>
                    </div>
                    <!--Deletes the post-->
                  <%= link_to 'Delete', post_element_path(@post, element), method:
                  :delete, class: 'btn btn-danger mt-2', data: {confirm: "Are you sure?" } %>
                  <% else %>
                    <%= form_with(model: [@post, element]) do |form| %>
                      <%= form.file_field :image %>
                      <div class="mt-3">
                        <%= form.submit "Save", class: "btn btn-primary" %>
                        <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                      </div>
                    <% end %>
                  <% end %>
                  </div>
                <% end %>
              <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
 <span>Posts</span>
 <!--Allows user to create a new post, takes user to the create post view-->
 <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
      <div class="card mb-3 post-card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-2">
              <!--Allows user to add a header image for their post-->
              <% if post.header_image.present? %>
              <div class="header_img" style ="background-image: url(<%=
               url_for(post.header_image) %>);"></div>
              <% end %>
            </div>
            <div class="col_md-10">
              <!--Displays the status of the post whether it's published or not-->
              <% if post.published? %>
              <span class='badge badge-primary'>Published</span>
              <% else %>
              <span class='badge badge-secondary'>Unpublished</span>
              <% end %>
              <!--Used for the post title-->
              <h5 class='card-title mb-1 text-dark'><%= post.title %></h5>
              <!--Used for the post description-->
              <p class='text-secondary mb-0'><%= post.description %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<div class="row">
  <div class="col md-4">

    <!--Back button-->
    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>

    <div class="card">
      <div class="card-header">
        <h6 class='card-title mb-0'>New Clothing Review</h6>
      </div>
      <!--sets up form for new post to be created-->
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BWProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- renders stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- renders navbar -->
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BWProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- renders stylesheet -->
    <<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light authors'>
    <div class="container">
      <!-- renders navbar -->
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BWProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- renders stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light readers <%= controller_name %> <%= action_name %>'>
    <div class="container">
      <!-- renders navbar -->
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/readers/home/index.html.erb
<h1>Welcome to BW Labels</h1>
<h4>The website where you can review clothes</h4>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-6 col-lg-4">
      <div class="card post-card">
        <!--Shows the post header image but it's shown in the style of a background image-->
        <div class="header-image" style="background-image: url(<%= url_for(post.header_image) %>)">
        </div>
        <div class="card-body d-flex flex-column">
          <!--Shows the post title-->
          <h5 class="card-title"><%= post.title %></h5>
          <!--Shows the text/paragraph information from the post-->
          <p class="card-text"><%= truncate(post.description, length: 250) %></p>
          <!--Button that allows user to click into the post view-->
          <%= link_to "Read Post", blog_post_path(post), class: 'btn btn-primary mt-auto' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/readers/posts/search.html.erb
<!-- app/views/travel/search.html.erb -->
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Country info</h4>
      <dl>
        <dt>Country</dt>
        <dd><%= @country['name'] %></dd>
        <dt>Capital</dt>
        <dd><%= @country['capital'] %></dd>
        <dt>Currency</dt>
        <dd><%= @country['currencies'].join(', ') %></dd>
        <dt>Timezone(s)</dt>
        <dd><%= @country['timezones'].join(', ') %></dd>
      </dl>
    </div>
    <div class="col-lg-6">
      <h4>Weather Info</h4>
      <dl>
        <% @weather['list'].each do |weather| %>
          <dt><%= weather['dt_txt'] %></dt>
          <dd>
            <strong>Min</strong> <%= to_fahrenheit weather['main']['temp_min'] %>
            <strong>Max</strong> <%= to_fahrenheit weather['main']['temp_max'] %>
          </dd>
        <% end %>
      </dl>
    </div>
  </div>
</div>

app/views/readers/posts/show.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="card post-card mb-5">
      <!--Shows the post image used for the -->
      <div class="header-image" style="background-image: url(<%= url_for(@post.header_image) %>)">
      </div>
      <div class="card-body">
        <div class="pl-5 pr-5 pt-4 pb-4">
          <!--Shows the post title-->
          <h1 class="card-title mb-5"><%= @post.title %></h1>
          <% @post.elements.each do |element| %>
          <!--Shows the post image-->
            <% if element.image? %>
            <div class="image-element mb-5">
              <%= image_tag(element.image) %>
            </div>
            <% else %>
            <div class="content-element mb-5">
              <%= element.content %>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
    <%= f.search_field :title_or_description_cont,
     placeholder: "Search...", class:"form-control me-2" %>
    <%= f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@posts.count, "Result")%></h1>
<div class="container">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@query, :title, "Title", default_order: :asc)%></th>
        <th><%= sort_link(@query, :description, "Description")%></th>
      </tr>
    </thead>
    <tbody>
        <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.description.truncate_words(25) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">BW Labels</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <!-- When Author is signed in this will be the menu-->
        <% if author_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_author_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Posts', posts_path, class: 'nav-link' %>
          </li>
          <ul class="navbar-nav">
            <!-- brings in search function -->
          <%= render 'search/form' %>
          </ul>
        <% else %>
        <!-- When user is not signed in they're a reader, this will be the menu-->
          <li class="nav-item">
            <%= link_to 'Register', new_author_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_author_session_path, class: 'nav-link' %>
          </li>
          <ul class="navbar-nav">
            <!-- brings in search function -->
          <%= render 'search/form' %>
          </ul>
        <% end %>
      </ul>
    </div>
</nav>